name: Promote file to release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
      file_path:
        description: 'Path to file in repo'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.event.inputs.file_path }}
          asset_name: $(basename ${{ github.event.inputs.file_path }})
          tag: ${{ github.event.inputs.tag }}
          overwrite: true
